inflr3/accounts/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('',
    url(r'^entrar/$', 'django.contrib.auth.views.login',
    {'template_name': 'accounts/login.html'}, name='login'),
    url(r'^cadastre-se/$','inflr3.accounts.views.register',name='register'),
    )

inflr3/store/urls.py
from django.conf.urls import patterns, include, url


urlpatterns = patterns('inflr3.store.views',
    url(r'^$', 'home', name='home'),
    url(r'^products/$', 'productlist', name='productlist'),
    url(r'^products/form/$', 'addproduct', name='addproduct'),
    url(r'^(?P<slug>[\w_-]+)/$', 'details', name='details'),

    )

inflr3/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^conta/', include('inflr3.accounts.urls', namespace='accounts')),
    url(r'^', include('inflr3.store.urls', namespace='store')),

)

inflr3/accounts/models.py
from django.db import models

# Create your models here.

inflr3/core/models.py
from django.db import models

# Create your models here.

inflr3/store/models.py
from django.db import models
from django.conf import settings
# Create your models here.

class ProductManager(models.Manager):

    def search(self,query):
        return self.get_queryset().filter(
            models.Q(name__incontains = query) | \
            models.Q(description__incotains = query)
        )

class Product(models.Model):

    name = models.CharField('Nome do Produto',max_length=100)
    slug = models.SlugField('Atalho')
    image = models.ImageField(upload_to='store/images',verbose_name='Imagem',null=True,blank=True)
    description= models.TextField()
    created_at = models.DateTimeField('Criado em ', auto_now_add=True)
    bought = models.BooleanField(blank=True)

    def __str__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('store:details',(),{'slug':self.slug})

    class Meta:
        verbose_name ='Produto'
        verbose_name_plural='Produtos'
        ordering =['name']


class Buy(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='Usuario',
        related_name='buy'
    )
    product = models.ForeignKey(
        Product, verbose_name='Produto', related_name='buy'
    )

inflr3/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.conf import settings
from django.http import HttpResponseRedirect
# Create your views here.

# def login(request):
#     return (request,'accounts/login.html')


def register(request):
    template_name = 'accounts/add_user.html'
    if request.method == "POST":
        form=UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(settings.LOGIN_URL)
    else:
        form = UserCreationForm()
    context = {
        'form': form
    }
    return render(request,template_name,context)

inflr3/core/views.py
from django.shortcuts import render

# Create your views here.

inflr3/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product
from .form import AddProduct
# Create your views here.


def home(request):
    products = Product.objects.all()
    template_name = 'store/home.html'
    context = {
        'products': products
    }

    return render(request, template_name, context)


def details(request, slug):

    product = get_object_or_404(Product, slug=slug)
    context = {
        'product': product
    }
    template_name = 'store/details.html'
    return render(request, template_name, context)


def productlist(request):
    products = Product.objects.all()
    template_name = 'store/productslist.html'
    context = {
        'products': products
    }
    return render(request, template_name, context)

def addproduct(request):

    template_name ='store/addproduct.html'

    if request.method == "POST":
        form = AddProduct(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            return redirect('store:productlist')
    else:
        form = AddProduct()
    return render(request, template_name,{'form':form})

inflr3/accounts/templates/accounts/add_user.html
{% extends "base2.html" %}

{% load static %}
{% block content%}
<div class="list-products">
	<form action="" method="post">
			{% csrf_token %}
			<fieldset>
				{{ form.non_field_errors }}

					{% for field in form %}
						<div class="login-input">

							{{ field.label_tag}}
							{{ field }}
							{{ field.errors }}
						</div>
					{% endfor %}
			<div class="login-button">
				 <button type="submit">Cadastre-se</button>
			</div>
			</fieldset>

		</form>



		</div>
{% endblock%}

inflr3/accounts/templates/accounts/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> Inflr Test </title>
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link rel="stylesheet" href="{% static 'css/material-design-iconic-font.css'%}">
	<meta name="author" content="Inflr">
	<meta name="description" content="Inflr">
	<meta name="keywords" content="Inflr">
	<meta name="viewport" content="initial-scale=1">
</head>
<body class="">

	<div class="login-container">
		<div class="login-title">
			Login
		</div>

		<form action="" method="post">
			{% csrf_token %}
			<fieldset>
				{{ form.non_field_errors }}

					{% for field in form %}
						<div class="login-input">

							{{ field.label_tag}}
							{{ field }}
							{{ field.errors }}
						</div>
					{% endfor %}
			<div class="login-button">
				 <button type="submit">Login</button>
			</div>
			</fieldset>

		</form>
		<div class="login-button">
				<a href="{% url 'accounts:register' %}"> Registrar </a>
		</div>
	</div>

</body>
</html>

inflr3/core/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> Inflr Test </title>
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" href="{% static 'css/material-design-iconic-font.css'%}">
	<meta name="author" content="Inflr">
	<meta name="description" content="Inflr">
	<meta name="keywords" content="Inflr">
	<meta name="viewport" content="initial-scale=1">
</head>
<body class="">

	<header class="header-wrapper">
		<div class="header-logo">
            <a href="{% url 'store:home'%}">
                <img src="{% static 'img/logo.png'%}" alt="">
            </a>

		</div>
		<div class="header-links">
			<div>Usuário: {{user.username}}</div>
			<div> <a href="{% url 'accounts:login'%}"> Login </a> </div>
			<div> <a href="{% url 'store:home'%}"> Items </a> </div>


		</div>
	</header>

	<div class="container">
		{% block content %}

        {% endblock %}
	</div>

</body>
</html>

inflr3/core/templates/base2.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title> Inflr Test </title>
	<link rel="stylesheet" href="{% static 'css/style.css'%}">
	<link rel="stylesheet" href="{% static 'css/material-design-iconic-font.css'%}">
	<meta name="author" content="Inflr">
	<meta name="description" content="Inflr">
	<meta name="keywords" content="Inflr">
	<meta name="viewport" content="initial-scale=1">
</head>
<body class="">

	<header class="header-wrapper">
		<div class="header-logo">
            <a href="{% url 'store:home'%}">
                <img src="{% static 'img/logo.png'%}" alt="">
            </a>

		</div>
		<div class="header-links">
			<div>Usuário: {{user.username}}</div>
			<div> <a href="{% url 'accounts:login'%}"> Login </a> </div>
			<div> <a href="{% url 'store:home'%}"> Items </a> </div>
			<div> <a href="{% url 'store:addproduct'%}"> Adicionar Item </a> </div>

		</div>
	</header>

	<div class="container">
		{% block content %}

        {% endblock %}
	</div>

</body>
</html>

inflr3/store/templates/store/addproduct.html
{% extends "base2.html" %}

{% load static %}
{% block content%}
<div class="list-products">
			<form action="" method="post">
				<div class="add-product">
					<div class="add-product-title">
						Adicionar Item
					</div>
						<form action="" method="post">
							{% csrf_token %}
							<fieldset>
								{{ form.non_field_errors }}

									{% for field in form %}
										<div class="login-input">

											{{ field.label_tag}}
											{{ field }}
											{{ field.errors }}
										</div>
									{% endfor %}
							<div class="login-button">
								 <button type="submit">Cadastrar</button>
							</div>
							</fieldset>

						</form>

					<!--<div class="add-product-input">-->
						<!--<input type="text" placeholder="Nome do item">-->
					<!--</div>-->
					<!--<div class="add-product-input">-->
						<!--<input type="text" placeholder="URL da imagem do item">-->
					<!--</div>-->
					<!--<div class="add-product-input">-->
						<!--<textarea name="" rows="1" placeholder="Descrição do item"></textarea>-->
					<!--</div>-->

					<!--<div class="add-product-button">-->
						<!--<a href="admin.html"> Cadastrar </a>-->
					<!--</div>-->
				</div>
			</form>
		</div>
{% endblock%}

inflr3/store/templates/store/details.html
{% extends "base.html" %}

{% load static %}

{% block content%}
    <div class="page-title">
                Detalhes do Produto
    </div>

            <div class="details-image"></div><!--

         --><div class="details-content">
                <div class="details-title">
                    {{ product.name }}
                </div>

                <div class="details-description">
                    {{product.description | linebreaks }}
                </div>

                <div class="details-buy">
                    <i class="zmdi zmdi-shopping-cart-plus"></i>
                    Comprar
                </div>
            </div>
{% endblock %}

inflr3/store/templates/store/home.html
{% extends "base.html" %}

{% load static %}
{% block content%}
<div class="page-title">
			Items comprados
		</div>
		<div class="items-comprados">
			<div class="items-comprados-container">
                    {% for product in products %}
                        {% if product.bought"%}
                             <div class="items-comprados-container">
                                <div class="item-each">
                                    <div class="item-image"></div>
                                    <div class="item-title">
                                        {{ product.name }}
                                    </div>
                                    <div class="item-description">
                                        {{ productt.description | linebreaks}}
                                    </div>
                                    <div class="item-buy">
                                        <div class="see-more">
                                            <a href="{{ product.get_absolute_url }}">Visualizar</a>
                                        </div>

                                    </div>
                                </div>
			                </div>
                        {% else %}

                        {% endif %}
                    {% endfor %}




			</div>

			<div class="divider"></div>

			<div class="page-title">
				Lista de Items
			</div>
            {% for product in products %}

                    <div class="items-comprados-container">
                        <div class="item-each">
                            <div class="item-image"></div>
                            <div class="item-title">
                                {{ product.name }}
                            </div>
                            <div class="item-description">
                                {{ productt.description | linebreaks}}
                            </div>
                            <div class="item-buy">
                                <div class="see-more">
                                    <a href="{{ product.get_absolute_url }}">Visualizar</a>
                                </div>
                                <div>
                                    <i class="zmdi zmdi-shopping-cart-plus"></i>
                                    Comprar{{}}
                                </div>
                            </div>
                        </div>
			        </div>

            {% endfor%}


		</div>
{% endblock %}

inflr3/store/templates/store/productslist.html
{% extends "base2.html" %}

{% load static %}

{% block content%}
<div class="container container-products">
	<div class="list-products">
		{% for product in products%}
				<div class="list-product-each">
					<div class="list-product-thumbnail"></div>
					<div class="list-product-title">
						{{ product.name }}
					</div>
					<div class="list-product-delete">
						Excluir <i class="zmdi zmdi-close"></i>
					</div>
					<div class="list-product-bought">
						{{user.name}}
					</div>
				</div>
		{% endfor%}
	</div>
</div>
{% endblock%}